substitutions:
  name: esphome-web-4fb244
  friendly_name: SMS FireBeetle ESP32 DFR0264

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0

  on_boot:
    priority: -100
    then:
      - output.turn_on: gpio_sensor
      - wait_until:
          condition:
            api.connected:
      - component.update: battery_voltage_uc_dfr0264
      - component.update: moisture_value_dfr0264
      - script.execute: deep_sleep_evaluation

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..." # YOUR KEY

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

# Set up wifi
wifi:
  fast_connect: True
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: "XX.XX.XX.XX" # YOUR STATIC IP
    gateway: "XX.XX.XX.XX" # YOUR GATEWAY IP
    subnet: "XX.XX.XX.XX" # YOUR SUBNET MASK

captive_portal:

deep_sleep:
  id: deep_sleep_enabled
  sleep_duration: 1h

binary_sensor:
  - platform: homeassistant
    id: prevent_deep_sleep
    entity_id: input_boolean.sms_esps_prevent_deep_sleep
    publish_initial_state: true

output:
  - platform: gpio
    pin: GPIO26
    id: gpio_sensor

sensor:
- platform: adc
  id: battery_voltage_uc_dfr0264
  name: "Battery voltage uC DFR0264"
  pin: GPIO36
  accuracy_decimals: 3
  attenuation: 11dB
  filters:
    - multiply: 2

- platform: adc
  id: moisture_value_dfr0264
  name: "Soil Moisture Voltage DFR0264"
  unit_of_measurement: "V"
  pin: GPIO35
  attenuation: 11dB
  accuracy_decimals: 2

script:
  - id: deep_sleep_evaluation
    mode: queued
    then:
      - output.turn_on: gpio_sensor
      - delay: 15s
      - component.update: battery_voltage_uc_dfr0264
      - component.update: moisture_value_dfr0264
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep            
          then:
            - logger.log: 'Deep Sleep Disabled'
            - component.update: battery_voltage_uc_dfr0264
            - component.update: moisture_value_dfr0264
            - delay: 30s
          else:
            - component.update: battery_voltage_uc_dfr0264
            - component.update: moisture_value_dfr0264
            - output.turn_off: gpio_sensor
            - delay: 3s
            - deep_sleep.enter: deep_sleep_enabled
      - script.execute: deep_sleep_evaluation
