esphome:
  name: esphome-web-f769b2
  friendly_name: SMS Firebeetle ESP8266

  on_boot:
    priority: -100
    then:
      - wait_until:
          condition:
            api.connected:
      - component.update: sms_esp8266_poswer_supply_voltage
      - component.update: sms_esp8266_soil_moisture_voltage
      - script.execute: deep_sleep_evaluation

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "..." # YOUR KEY

ota:

wifi:
  fast_connect: True
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

deep_sleep:
  id: deep_sleep_enabled
  sleep_duration: 30min
  
# According Helper Button is required
binary_sensor:
  - platform: homeassistant
    id: prevent_deep_sleep_sms
    name: Deep Sleep Mode
    entity_id: input_boolean.sms_esps_prevent_deep_sleep

sensor:
- platform: adc
  id: sms_esp8266_soil_moisture_voltage
  name: "Soil Moisture Voltage"
  pin: A0
  accuracy_decimals: 2
  filters:
    - multiply: 3.2 # DRF Firebeetle has an onboad voltage divider

- platform: ina3221
  address: 0x40
  i2c_id: e1
  id: sms_esp8266_poswer_supply_voltage
  channel_1:
    shunt_resistance: 0.1 ohm
    bus_voltage:
      name: "INA3221 Channel 1 Bus Voltage"

i2c:
  - sda: GPIO04
    scl: GPIO05
    id: e1

script:
  - id: deep_sleep_evaluation
    mode: queued
    then:
      - delay: 12s
      - component.update: sms_esp8266_poswer_supply_voltage
      - component.update: sms_esp8266_soil_moisture_voltage
      - logger.log:
          format: "Deep Sleep Status: %d"
          args: [ 'id(prevent_deep_sleep_sms).state' ]
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep_sms
          then:
            - logger.log: 'Deep Sleep Disabled'
            - component.update: sms_esp8266_poswer_supply_voltage
            - component.update: sms_esp8266_soil_moisture_voltage
            - delay: 2s
          else:
            - component.update: sms_esp8266_poswer_supply_voltage
            - component.update: sms_esp8266_soil_moisture_voltage
            - delay: 3s
            - deep_sleep.enter: deep_sleep_enabled
      - script.execute: deep_sleep_evaluation
